use_frameworks!

platform :ios, '8.0'

target 'LMMonitor_Example' do
  pod 'LMMonitor', :path => '../'

  target 'LMMonitor_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase'
  end
end
